### ISSUE TITLE
Import accessibility fixes back to the template

### ISSUE THREAD

**Issue by mjskay** [journalovi/jovi-template-quarto#12]
Once https://github.com/journalovi/2023-park-gatherplots/issues/10 is resolved we should import any relevant accessibility fixes @domoritz and @nickelm come up with to this template.

**Comment by cscheid** [comment]
changes to the HTML format block, something like

```
format:
  html:
    citations-hover: false
    footnotes-hover: false
    crossrefs-hover: false
```

**Comment by mjskay** [comment]
Also standalone stuff:

```yaml
    embed-resources: true
    self-contained-math: true
    html-math-method: katex
```

To fix #7 as best we can for now
